  source 'https://rubygems.org'
    gem 'sinatra-activerecord'
    gem 'sqlite3'
    gem 'rake'
    gem 'logger'
    gem 'bcrypt'
    gem 'rack-flash3'
    gem 'will_paginate'
    
    group :test do
      gem 'rspec'
      gem 'simplecov'
    end
    
   github 'sinatra/sinatra', branch: 'main' do
    gem 'sinatra'
    gem 'sinatra-contrib'

  end